services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/app:/App/data
      - ./data/keys:/root/.aspnet/DataProtection-Keys
    ports:
      - ${LUBELOGGER_PORT}:8080