services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    env_file: 
      - .env
    ## the container's port must be the same with the STASH_PORT in the environment section
    ports:
      - ${STASHAPP_PORT}:9999
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/config:/root/.stash
      ## Point this at your collection.
      ## The left side is where your collection is on your host, the right side is where it will be in stash.
      - ${STASHAPP_DATA_PATH}:/data
      ## This is where your stash's metadata lives
      - ./data/metadata:/metadata
      ## Any other cache content.
      - ./data/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - ./data/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - ./data/generated:/generated